import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:iconsax/iconsax.dart';
import '../../models/order.dart';
import '../../provider/order_provider.dart';
import '../../provider/doctor_provider.dart';
import '../../provider/chemist_shop_provider.dart';
import '../../provider/distributor_provider.dart';
import '../../theme/app_theme.dart';
import '../../widgets/app_bar.dart';

class CreateOrderScreen extends ConsumerStatefulWidget {
  const CreateOrderScreen({super.key});

  @override
  ConsumerState<CreateOrderScreen> createState() => _CreateOrderScreenState();
}

class _CreateOrderScreenState extends ConsumerState<CreateOrderScreen> {
  final _formKey = GlobalKey<FormState>();
  
  String? _selectedDoctorId;
  String? _selectedChemistShopId;
  String? _selectedDistributorId;
  DateTime? _deliveryDate;
  final _notesController = TextEditingController();
  
  final List<_MedicineFormItem> _medicines = [];

  @override
  void initState() {
    super.initState();
    // Start with one empty medicine item
    _addMedicine();
  }

  @override
  void dispose() {
    _notesController.dispose();
    for (var medicine in _medicines) {
      medicine.dispose();
    }
    super.dispose();
  }

  void _addMedicine() {
    setState(() {
      _medicines.add(_MedicineFormItem());
    });
  }

  void _removeMedicine(int index) {
    setState(() {
      _medicines[index].dispose();
      _medicines.removeAt(index);
    });
  }

  void _submitOrder() {
    if (_formKey.currentState!.validate()) {
      if (_selectedDoctorId == null) {
        _showErrorSnackBar('Please select a doctor');
        return;
      }
      if (_selectedChemistShopId == null) {
        _showErrorSnackBar('Please select a chemist shop');
        return;
      }
      if (_selectedDistributorId == null) {
        _showErrorSnackBar('Please select a distributor');
        return;
      }
      if (_medicines.isEmpty) {
        _showErrorSnackBar('Please add at least one medicine');
        return;
      }

      // Create medicine list
      final medicines = _medicines
          .where((item) => item.nameController.text.isNotEmpty)
          .map((item) => OrderMedicine(
                id: DateTime.now().millisecondsSinceEpoch.toString(),
                name: item.nameController.text,
                quantity: int.tryParse(item.quantityController.text) ?? 0,
                unit: item.unitController.text.isNotEmpty
                    ? item.unitController.text
                    : null,
                batchNumber: item.batchController.text.isNotEmpty
                    ? item.batchController.text
                    : null,
              ))
          .toList();

      if (medicines.isEmpty) {
        _showErrorSnackBar('Please add at least one valid medicine');
        return;
      }

      // Create order
      final order = Order(
        id: '', // Will be generated by notifier
        doctorId: _selectedDoctorId!,
        chemistShopId: _selectedChemistShopId!,
        distributorId: _selectedDistributorId!,
        medicines: medicines,
        status: OrderStatus.pending,
        orderDate: DateTime.now(),
        deliveryDate: _deliveryDate,
        notes: _notesController.text.isNotEmpty ? _notesController.text : null,
      );

      // Add to state
      ref.read(orderProvider.notifier).addOrder(order);

      // Show success message
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Order created successfully'),
          backgroundColor: AppColors.success,
        ),
      );

      // Navigate back
      context.pop();
    }
  }

  void _showErrorSnackBar(String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: AppColors.error,
      ),
    );
  }

  Future<void> _selectDeliveryDate() async {
    final date = await showDatePicker(
      context: context,
      initialDate: _deliveryDate ?? DateTime.now().add(const Duration(days: 1)),
      firstDate: DateTime.now(),
      lastDate: DateTime.now().add(const Duration(days: 365)),
      builder: (context, child) {
        return Theme(
          data: Theme.of(context).copyWith(
            colorScheme: const ColorScheme.light(
              primary: AppColors.primary,
            ),
          ),
          child: child!,
        );
      },
    );

    if (date != null) {
      setState(() {
        _deliveryDate = date;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    final doctors = ref.watch(doctorProvider);
    final chemistShops = ref.watch(chemistShopProvider);
    final distributors = ref.watch(distributorProvider);

    return Scaffold(
      backgroundColor: AppColors.surface,
      appBar: MRAppBar(
        showBack: true,
        showActions: false,
        titleText: 'Create New Order',
        subtitleText: 'Fill in the order details',
        onBack: () => context.pop(),
      ),
      body: Form(
        key: _formKey,
        child: ListView(
          padding: const EdgeInsets.all(AppSpacing.md),
          children: [
            // Doctor Selection
            _buildSectionHeader('Select Doctor', Iconsax.user),
            const SizedBox(height: AppSpacing.sm),
            DropdownButtonFormField<String>(
              value: _selectedDoctorId,
              decoration: _buildInputDecoration(
                hintText: 'Choose a doctor',
                prefixIcon: Iconsax.briefcase,
              ),
              items: doctors.map((doctor) {
                return DropdownMenuItem(
                  value: doctor.id,
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Text(
                        doctor.name,
                        style: AppTypography.body.copyWith(
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                      Text(
                        doctor.specialization,
                        style: AppTypography.bodySmall.copyWith(
                          color: AppColors.quaternary,
                          fontSize: 12,
                        ),
                      ),
                    ],
                  ),
                );
              }).toList(),
              onChanged: (value) {
                setState(() {
                  _selectedDoctorId = value;
                });
              },
              validator: (value) {
                if (value == null || value.isEmpty) {
                  return 'Please select a doctor';
                }
                return null;
              },
            ),
            const SizedBox(height: AppSpacing.lg),

            // Chemist Shop Selection
            _buildSectionHeader('Delivery Location', Iconsax.shop),
            const SizedBox(height: AppSpacing.sm),
            DropdownButtonFormField<String>(
              value: _selectedChemistShopId,
              decoration: _buildInputDecoration(
                hintText: 'Choose a chemist shop',
                prefixIcon: Iconsax.location,
              ),
              items: chemistShops.map((shop) {
                return DropdownMenuItem(
                  value: shop.id,
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Text(
                        shop.name,
                        style: AppTypography.body.copyWith(
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                      Text(
                        shop.location,
                        style: AppTypography.bodySmall.copyWith(
                          color: AppColors.quaternary,
                          fontSize: 12,
                        ),
                        maxLines: 1,
                        overflow: TextOverflow.ellipsis,
                      ),
                    ],
                  ),
                );
              }).toList(),
              onChanged: (value) {
                setState(() {
                  _selectedChemistShopId = value;
                });
              },
              validator: (value) {
                if (value == null || value.isEmpty) {
                  return 'Please select a chemist shop';
                }
                return null;
              },
            ),
            const SizedBox(height: AppSpacing.lg),

            // Distributor Selection
            _buildSectionHeader('Select Distributor', Iconsax.truck),
            const SizedBox(height: AppSpacing.sm),
            DropdownButtonFormField<String>(
              value: _selectedDistributorId,
              decoration: _buildInputDecoration(
                hintText: 'Choose a distributor',
                prefixIcon: Iconsax.box,
              ),
              items: distributors.map((distributor) {
                return DropdownMenuItem(
                  value: distributor.id,
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Text(
                        distributor.name,
                        style: AppTypography.body.copyWith(
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                      Text(
                        'Delivery: ${distributor.deliveryTime}',
                        style: AppTypography.bodySmall.copyWith(
                          color: AppColors.quaternary,
                          fontSize: 12,
                        ),
                      ),
                    ],
                  ),
                );
              }).toList(),
              onChanged: (value) {
                setState(() {
                  _selectedDistributorId = value;
                });
              },
              validator: (value) {
                if (value == null || value.isEmpty) {
                  return 'Please select a distributor';
                }
                return null;
              },
            ),
            const SizedBox(height: AppSpacing.lg),

            // Delivery Date
            _buildSectionHeader('Expected Delivery Date (Optional)', Iconsax.calendar),
            const SizedBox(height: AppSpacing.sm),
            InkWell(
              onTap: _selectDeliveryDate,
              child: Container(
                padding: const EdgeInsets.all(AppSpacing.md),
                decoration: BoxDecoration(
                  color: AppColors.white,
                  borderRadius: BorderRadius.circular(AppBorderRadius.md),
                  border: Border.all(color: AppColors.border),
                ),
                child: Row(
                  children: [
                    const Icon(Iconsax.calendar, color: AppColors.primary),
                    const SizedBox(width: AppSpacing.md),
                    Expanded(
                      child: Text(
                        _deliveryDate != null
                            ? '${_deliveryDate!.day}/${_deliveryDate!.month}/${_deliveryDate!.year}'
                            : 'Select delivery date',
                        style: AppTypography.body.copyWith(
                          color: _deliveryDate != null
                              ? AppColors.black
                              : AppColors.quaternary,
                        ),
                      ),
                    ),
                    if (_deliveryDate != null)
                      IconButton(
                        icon: const Icon(Icons.clear, size: 20),
                        onPressed: () {
                          setState(() {
                            _deliveryDate = null;
                          });
                        },
                      ),
                  ],
                ),
              ),
            ),
            const SizedBox(height: AppSpacing.lg),

            // Medicines Section
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                _buildSectionHeader('Medicines', Iconsax.health),
                InkWell(
                  onTap: _addMedicine,
                  child: Padding(
                    padding: const EdgeInsets.symmetric(horizontal: AppSpacing.sm),
                    child: Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        const Icon(Iconsax.add_circle, size: 20, color: AppColors.primary),
                        const SizedBox(width: AppSpacing.xs),
                        Text(
                          'Add Medicine',
                          style: AppTypography.bodySmall.copyWith(
                            color: AppColors.primary,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
            const SizedBox(height: AppSpacing.sm),

            // Medicine Items
            ..._medicines.asMap().entries.map((entry) {
              final index = entry.key;
              final medicine = entry.value;
              return _buildMedicineItem(medicine, index);
            }),
            const SizedBox(height: AppSpacing.lg),

            // Notes
            _buildSectionHeader('Notes (Optional)', Iconsax.document_text),
            const SizedBox(height: AppSpacing.sm),
            TextFormField(
              controller: _notesController,
              maxLines: 4,
              decoration: _buildInputDecoration(
                hintText: 'Add any special instructions or notes...',
                prefixIcon: null,
              ),
            ),
            const SizedBox(height: AppSpacing.xl),

            // Submit Button
            ElevatedButton(
              onPressed: _submitOrder,
              style: ElevatedButton.styleFrom(
                backgroundColor: AppColors.primary,
                foregroundColor: AppColors.white,
                padding: const EdgeInsets.symmetric(vertical: AppSpacing.md),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(AppBorderRadius.lg),
                ),
              ),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  const Icon(Iconsax.tick_circle),
                  const SizedBox(width: AppSpacing.sm),
                  Text(
                    'Create Order',
                    style: AppTypography.tagline.copyWith(
                      color: AppColors.white,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: AppSpacing.md),
          ],
        ),
      ),
    );
  }

  Widget _buildSectionHeader(String title, IconData icon) {
    return Row(
      children: [
        Icon(icon, color: AppColors.primary, size: 20),
        const SizedBox(width: AppSpacing.sm),
        Text(
          title,
          style: AppTypography.tagline.copyWith(
            color: AppColors.primary,
            fontWeight: FontWeight.bold,
          ),
        ),
      ],
    );
  }

  Widget _buildMedicineItem(_MedicineFormItem medicine, int index) {
    return Container(
      margin: const EdgeInsets.only(bottom: AppSpacing.md),
      padding: const EdgeInsets.all(AppSpacing.md),
      decoration: BoxDecoration(
        color: AppColors.white,
        borderRadius: BorderRadius.circular(AppBorderRadius.md),
        border: Border.all(color: AppColors.border),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                'Medicine ${index + 1}',
                style: AppTypography.body.copyWith(
                  fontWeight: FontWeight.w600,
                  color: AppColors.primary,
                ),
              ),
              if (_medicines.length > 1)
                IconButton(
                  icon: const Icon(Iconsax.trash, color: AppColors.error),
                  onPressed: () => _removeMedicine(index),
                ),
            ],
          ),
          const SizedBox(height: AppSpacing.sm),
          TextFormField(
            controller: medicine.nameController,
            decoration: _buildInputDecoration(
              hintText: 'Medicine Name',
              prefixIcon: Iconsax.health,
            ),
            validator: (value) {
              if (value == null || value.isEmpty) {
                return 'Please enter medicine name';
              }
              return null;
            },
          ),
          const SizedBox(height: AppSpacing.sm),
          Row(
            children: [
              Expanded(
                flex: 2,
                child: TextFormField(
                  controller: medicine.quantityController,
                  keyboardType: TextInputType.number,
                  decoration: _buildInputDecoration(
                    hintText: 'Quantity',
                    prefixIcon: Iconsax.box_1,
                  ),
                  validator: (value) {
                    if (value == null || value.isEmpty) {
                      return 'Required';
                    }
                    if (int.tryParse(value) == null) {
                      return 'Invalid';
                    }
                    return null;
                  },
                ),
              ),
              const SizedBox(width: AppSpacing.sm),
              Expanded(
                flex: 1,
                child: TextFormField(
                  controller: medicine.unitController,
                  decoration: _buildInputDecoration(
                    hintText: 'Unit',
                    prefixIcon: null,
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: AppSpacing.sm),
          TextFormField(
            controller: medicine.batchController,
            decoration: _buildInputDecoration(
              hintText: 'Batch Number (Optional)',
              prefixIcon: Iconsax.barcode,
            ),
          ),
        ],
      ),
    );
  }

  InputDecoration _buildInputDecoration({
    required String hintText,
    IconData? prefixIcon,
  }) {
    return InputDecoration(
      hintText: hintText,
      hintStyle: AppTypography.body.copyWith(
        color: AppColors.quaternary,
      ),
      prefixIcon: prefixIcon != null ? Icon(prefixIcon, color: AppColors.primary) : null,
      filled: true,
      fillColor: AppColors.white,
      border: OutlineInputBorder(
        borderRadius: BorderRadius.circular(AppBorderRadius.md),
        borderSide: const BorderSide(color: AppColors.border),
      ),
      enabledBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(AppBorderRadius.md),
        borderSide: const BorderSide(color: AppColors.border),
      ),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(AppBorderRadius.md),
        borderSide: const BorderSide(color: AppColors.primary, width: 2),
      ),
      errorBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(AppBorderRadius.md),
        borderSide: const BorderSide(color: AppColors.error),
      ),
      contentPadding: const EdgeInsets.symmetric(
        horizontal: AppSpacing.md,
        vertical: AppSpacing.md,
      ),
    );
  }
}

class _MedicineFormItem {
  final TextEditingController nameController = TextEditingController();
  final TextEditingController quantityController = TextEditingController();
  final TextEditingController unitController = TextEditingController();
  final TextEditingController batchController = TextEditingController();

  void dispose() {
    nameController.dispose();
    quantityController.dispose();
    unitController.dispose();
    batchController.dispose();
  }
}
